---
# Docker User
dockerUser: geoffh1977
license: gnu-gpl-v3.0

# Source Build Variables
buildImageName: alpine
buildImageVersion: latest

# Final Image Variables
finalImageName: consul
finalImageVersion: 1.4.4

# Application Variables
appName: Hashicorp Consul